### ISSUE TITLE
Thanks for this mic module! I have a question; not actually an issue, but you have no other means of contact lol

### ISSUE THREAD

**Issue by krompus** [rototrash/polybar-mic#1]
I tried contacting you on your discord, from your github website but `rototrash#9000` wasn't found. Maybe the number has changed because you don't have Nitro anymore? Consider updating your contact info. :)

Your polybar mic mute toggle/icon helped me a lot with my stream setup; I have a keybind to toggle mute but sometimes I'll mute myself and forget to unmute when I come back, this lets me easily see the current status, and the mouse functionality is a bonus. Thanks! 

I'd just like to know how you got the module to be a static width with the two icons that have different widths; my module changes width when toggled and it's a minor eyesore to see it nudge my other modules to the side. Not sure if there's some "minimum module width" setting?

Also, do you know if there's any way to have it change colour when toggled? Red when the mic is active, grey when muted, for example.

Thanks again!

**Comment by siddrs** [comment]
To address the width issue, there could be many reasons as to why it is happening.
Can you discord me your polybar config files at `rototrash#0900`? I'll take a look at them and get back to you as soon as I can.

Also thanks for pointing out the wrong username on the website lol, it's just my dumbass who got it wrong, it is #0900 and not #9000 lmao.

**Comment by krompus** [comment]
Hey thanks for replying! I tried to send you a DM in Discord, I think I have to add you as a friend first? It says you're not accepting friend requests, so I was unable to.

In any case, I've made my font smaller and it's not changing width anymore. I'm just wondering if it's possible to change the icon colour depending on the state. Example: Grey for mic muted, red for mic active.

**Comment by krompus** [comment]
Update: I'm now using `"   "` (space) to represent the muted mic, and a red mic icon when the mic is active, so I can just look for the red dot in my peripheral vision, perfect.

I also have a little script to automatically enter my password for the `click-right` updater:

    #!/bin/bash
    urxvt -geometry 50x15 -title yay! -e yay &
    sleep 0.2
    xdotool type --clearmodifiers 'PASSWORD'
    sleep 0.2
    xdotool key Return

That window is moved to the corner in my i3wm config: `	for_window [title="^yay!$"] floating enable, sticky enable, move --no-auto-back-and-forth to output DisplayPort-2, move absolute position 1548 843`
